apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ug6byiegg-nodejs 
  janus-idp.io/tekton: ug6byiegg-nodejs
  backstage.io/kubernetes-id: ug6byiegg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ug6byiegg-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  