apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ug6byiegg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ug6byiegg-nodejs 
  name: ug6byiegg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ug6byiegg-nodejs 
